### ISSUE TITLE
Error handling for invalid session times

### ISSUE THREAD

**Issue by Yongbeom-Kim** [Yongbeom-Kim/ped#3]
Inputting commands such as `session 1 s/mon 25:00` gives an error in the console, but said error is not handled. Same error for commands such as `session 2 s/fri 10:61`.

```sh
Caused by: java.time.DateTimeException: Invalid value for HourOfDay (valid values 0 - 23): 25
        at java.base/java.time.temporal.ValueRange.checkValidIntValue(ValueRange.java:338)
        at java.base/java.time.temporal.ChronoField.checkValidIntValue(ChronoField.java:737)
        at java.base/java.time.format.Parsed.resolveTime(Parsed.java:616)
        at java.base/java.time.format.Parsed.resolveTimeLenient(Parsed.java:581)
        at java.base/java.time.format.Parsed.resolve(Parsed.java:266)
        at java.base/java.time.format.DateTimeParseContext.toResolved(DateTimeParseContext.java:331)
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2062)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1958)
        ... 63 more
```

**Comment by phyliciachristel** [comment]
Hi, this was updated already and re-released before 10am yesterday, so you should not have encountered this issue. Did you download an old jar file instead?
